url=jdbc:mysql://localhost:3306/vinilostoredb_in4cm?useSSL=false&serverTimezone=UTC
user=IN4CM
password=#NdimAM4

db.url=jdbc:mysql://localhost:3306/vinilostoredb_in4cm?useSSL=false&serverTimezone=UTC
db.user=IN4CM
db.password=#NdimAM4
